Integrate with the API to get the API token
FairwindsOps/goldilocks pull request #503
Opened 2022-08-16 18:53 UTC by hieptl

This PR fixes #

## Checklist
* [x] I have signed the CLA
* [x] I have updated/added any relevant documentation

## Description
### What's the goal of this PR?

* Integrate with the Insights API to get the API token.

### What changes did you make?

* Integrate with the below API endpoint

```js
POST @ /v0/oss/users

Request Body Example:
{
  "email": "oss.user@gmail.com",
  "project": "goldilocks"
}
```

### What alternative solution should we consider, if any?

* none

2022-08-16 19:48 UTC, sudermanjr requested changes
Minor change inline, holding off on further review until #501 is merged and this branch is rebased.

2022-08-17 10:37 UTC, hieptl commented on cmd/dashboard.go
> +	dashboardCmd.PersistentFlags().StringVar(&insightsHost, "insightshost", "https://insights.fairwinds.com", "Insights host the dashboard is connected.")
Hi Andy, I updated the code. Thank you for your feedback!

2022-08-17 15:01 UTC, hieptl commented on cmd/dashboard.go
> +	dashboardCmd.PersistentFlags().StringVar(&insightsHost, "insights-host", "https://insights.fairwinds.com", "Insights host the dashboard is connected.")
I updated the code. Thank you

2022-08-18 16:14 UTC, rbren commented on pkg/dashboard/templates/dashboard.gohtml
> +    }
```suggestion
    window.INSIGHTS_HOST = "{{ .Data.InsightsHost }}"
```
we don't need the `onload`

2022-08-18 16:22 UTC, rbren commented
I shouldn't be seeing the API key box yet, right? It just triggers the email?

2022-08-18 16:23 UTC, rbren approved these changes

2022-08-18 17:34 UTC, hieptl commented
> I shouldn't be seeing the API key box yet, right? It just triggers the email?

Yes, the API Token section will be developed in another PR. Thank you!

2022-08-18 17:35 UTC, merged