feat(.goreleaser.yml): add sha256 check to release notes
FairwindsOps/goldilocks pull request #604
Opened 2023-05-04 13:43 UTC by arthurzenika

Improve commands so that the checksum of the downloaded file is checked before cosign is checked.

This PR fixes #

## Checklist
* [ ] I have signed the CLA
* [ ] I have updated/added any relevant documentation

## Description
### What's the goal of this PR?

### What changes did you make?

### What alternative solution should we consider, if any?

2023-05-04 13:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FairwindsOps/goldilocks?pullRequest=604) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FairwindsOps/goldilocks?pullRequest=604) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FairwindsOps/goldilocks?pullRequest=604) it.</sub>

2023-05-04 13:59 UTC, sudermanjr approved these changes
Thanks!

2023-05-04 14:07 UTC, arthurzenika commented
While I'm at it (and maybe I should describe this in an issue), it would be even nicer if the generated notes would include the version, for example for the last release : 

```
sha256sum -c goldilocks_4.7.2_checksums.txt --ignore-missing
cosign verify-blob goldilocks_4.7.2_checksums.txt --signature=goldilocks_4.7.2_checksums.txt.sig  --key https://artifacts.fairwinds.com/cosign.pub
```

not familiar with gorelease features though

2023-05-04 15:01 UTC, sudermanjr commented
You should be able to use the template placeholder `{{.Version}}` in the release note footer, looking here: https://goreleaser.com/customization/release/?h=release

2023-05-26 20:04 UTC, sudermanjr requested changes

2023-05-26 20:04 UTC, sudermanjr commented on .goreleaser.yml
> +    sha256sum -c checksums.txt --ignore-missing
```suggestion
    sha256sum -c goldilocks_v{{ .Major }}.{{ .Minor }}.{{ .Patch }}_checksums.txt --ignore-missing
```

2023-05-26 20:04 UTC, sudermanjr commented on .goreleaser.yml
>      cosign verify-blob checksums.txt --signature=checksums.txt.sig  --key https://artifacts.fairwinds.com/cosign.pub
```suggestion
    cosign verify-blob goldilocks_v{{ .Major }}.{{ .Minor }}.{{ .Patch }}_checksums.txt --signature=goldilocks_v{{ .Major }}.{{ .Minor }}.{{ .Patch }}_checksums.txt.sig  --key https://artifacts.fairwinds.com/cosign.pub
```

2023-05-30 16:56 UTC, sudermanjr approved these changes
Thanks!

2023-05-30 17:10 UTC, merged

2023-05-30 17:31 UTC, sudermanjr commented
Latest release notes are much nicer. Thanks again!