Added option to use VpaMinReplicasAnnotation from labels
FairwindsOps/goldilocks pull request #720
Opened 2024-07-21 20:59 UTC by devantler

This PR adds the option of using `goldilocks.fairwinds.com/vpa-min-replicas: X` as a label.

## Checklist
* [ ] I have signed the CLA
* [ ] I have updated/added any relevant documentation

## Description

Currently it is not possible to set vpa-min-relplicas with labels, like it is with some of the other options. This fix should ensure that is also the case for `vpa-min-replicas`

### What's the goal of this PR?

To support labels for `vpa-min-replicas`

### What changes did you make?

I added an if/else statement in the code where this was needed. The solution was inspired by how this is implemented other places in the code. Feel free to change it to your liking!

### What alternative solution should we consider, if any?

blank

2024-07-21 20:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FairwindsOps/goldilocks?pullRequest=720) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FairwindsOps/goldilocks?pullRequest=720) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FairwindsOps/goldilocks?pullRequest=720) it.</sub>

2024-07-22 14:55 UTC, sudermanjr commented on pkg/vpa/vpa.go
> +	} else if val, ok := accessor.GetLabels()[utils.VpaMinReplicasAnnotation]; ok {
Sorry, am I missing something here? This looks exactly the same as the previous if statement.

2024-07-22 17:26 UTC, sudermanjr requested changes
I don't love only doing this for the minReplicas and not the other VPA settings. Can you make sure that all settings are updated?

2024-07-22 18:52 UTC, devantler commented
Sure, i'll have a look at it as soon as possible ☀️🕶️

2024-07-24 19:32 UTC, devantler commented
@sudermanjr I made a search for all cases that uses the `accessor.GetAnnotations()` method, and only found one more that was missing an `else` condition for retrieving the key/value from labels. The rest had both annotations and labels supported, where annotations is prioritized if both are set. 

I believe that should be all, so I have rerequested a review ✌🏻

2024-07-25 19:20 UTC, sudermanjr commented
Looks good. Now I need to figure out why the CI won't run

2024-07-26 15:22 UTC, sudermanjr approved these changes

2024-07-29 16:18 UTC, merged